<a href="https://colab.research.google.com/github/kzdanowski/KGN_Programowanie2/blob/main/Lab/Numpy_linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# Rozwiązania do zadań z pliku P2Lab05_numpy.pdf

In [2]:
#  1
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

dot = A@B
normA = np.linalg.norm(A)
normB = np.linalg.norm(B)

cos_theta = dot / (normA * normB)
print(cos_theta)


0.9746318461970762


In [3]:
# 2
X = np.random.rand(5, 3)
print(X)
print(X.mean(axis=0))
X - X.mean(axis=0)


[[0.97918325 0.04883449 0.30347959]
 [0.84461293 0.00729588 0.68473916]
 [0.62534944 0.76632995 0.24241214]
 [0.56893465 0.84283506 0.79148942]
 [0.18260547 0.65266134 0.0511267 ]]
[0.64013715 0.46359134 0.4146494 ]


array([[ 0.3390461 , -0.41475685, -0.11116981],
       [ 0.20447578, -0.45629546,  0.27008976],
       [-0.0147877 ,  0.3027386 , -0.17223727],
       [-0.07120249,  0.37924372,  0.37684002],
       [-0.45753168,  0.18907   , -0.3635227 ]])

In [4]:
# 3
y_true = np.array([1, 2, 3])
y_pred = np.array([1.1, 1.9, 3.2])

mse = np.mean((y_true - y_pred) ** 2)
print(mse)
a = (y_true - y_pred).mean()
a**2

0.020000000000000035


np.float64(0.004444444444444451)

In [5]:
# 4
v = np.array([3, 4])

v_normalized = v / np.linalg.norm(v)
print(v_normalized)

# sprawdzenie
print(np.linalg.norm(v_normalized))



[0.6 0.8]
1.0


In [6]:
# 5
M = np.random.rand(10, 2)
P = np.array([0.5, 0.5])
print(M)
print(P)

distances = np.linalg.norm(M - P, axis=1)
print(M - P)
print(distances)


[[0.15605217 0.9490442 ]
 [0.18786054 0.85591231]
 [0.82971429 0.12851381]
 [0.13852078 0.85346912]
 [0.11670944 0.32672172]
 [0.94672773 0.56802082]
 [0.98406561 0.86759683]
 [0.45229602 0.64027389]
 [0.09554888 0.02924737]
 [0.84341374 0.77361204]]
[0.5 0.5]
[[-0.34394783  0.4490442 ]
 [-0.31213946  0.35591231]
 [ 0.32971429 -0.37148619]
 [-0.36147922  0.35346912]
 [-0.38329056 -0.17327828]
 [ 0.44672773  0.06802082]
 [ 0.48406561  0.36759683]
 [-0.04770398  0.14027389]
 [-0.40445112 -0.47075263]
 [ 0.34341374  0.27361204]]
[0.5656331  0.47339689 0.49670263 0.50557655 0.42063882 0.45187663
 0.60782148 0.14816354 0.62063576 0.43908603]


In [7]:
# 6
x = np.array([-2, -1, 0, 1, 2])

relu = np.maximum(0, x)
print(relu * (x > 0))

[0 0 0 1 2]


In [8]:
# 7
x = np.array([1, 2,5,5,5,5,5, 2, 3, 100])

mu = np.mean(x)
sigma = np.std(x)

mask = np.abs(x - mu) >= 2 * sigma
outliers = x[mask]

print(outliers)

[100]
