<a href="https://colab.research.google.com/github/kzdanowski/KGN_Programowanie2/blob/main/Lab/P2Lab06_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy i Pandas – generowanie i analiza danych

## 1. Cel zajęć

Celem jest opanowanie:
- generowania danych syntetycznych (różne rozkłady),
- kontroli losowości (seed),
- pracy na tablicach NumPy,
- przekształcania danych do struktur Pandas,
- podstawowej analizy danych.

---

## 2. NumPy – generowanie danych

NumPy służy głównie do pracy na tablicach numerycznych i jest podstawą dla Pandas.

Kluczowe funkcje:

np.array() – tworzy tablicę z listy lub innej struktury.

np.arange(start, stop, step) – generuje ciąg liczb (jak range, ale zwraca tablicę).

np.linspace(start, stop, num) – generuje określoną liczbę punktów w przedziale.

np.random.rand(n, m) – losowe liczby z rozkładu jednostajnego [0,1).

np.random.randn(n, m) – liczby z rozkładu normalnego (średnia 0, wariancja 1).

np.random.randint(low, high, size) – losowe liczby całkowite.

np.random.choice(a, size) – losowy wybór elementów z listy/zbioru.

np.random.seed(42) - ustala stałość generowanych danych losowych


## 3. Pandas – struktury danych i przekształcenia

Pandas operuje na danych tabelarycznych.

Podstawowe obiekty:

pd.Series – jednowymiarowa struktura danych.
pd.DataFrame – tabela (wiersze i kolumny).

Kluczowe funkcje:

pd.DataFrame(data) – tworzy tabelę z danych (np. słownika lub tablicy).

df.head(n) – podgląd pierwszych wierszy.

df.describe() – statystyki opisowe.

df.info() – informacje o typach danych.

df['kolumna'] – dostęp do kolumny.

df.mean(), df.std() – podstawowe statystyki.

pd.concat([df1, df2]) – łączenie danych.

df.apply(func) – zastosowanie funkcji do kolumn.





## 4. Przykład 1 – generowanie prostego zbioru danych

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

wiek = np.random.randint(18, 65, 100)
dochód = np.random.normal(5000, 1500, 100)

df = pd.DataFrame({
    "wiek": wiek,
    "dochód": dochód
})

print(df.head())
print(df.describe())

   wiek       dochód
0    56  5954.457663
1    46  3639.918997
2    32  5714.063881
3    60  6955.491903
4    25  5317.380518
            wiek       dochód
count  100.00000   100.000000
mean    40.88000  5102.764316
std     13.99082  1496.584209
min     18.00000  2090.133172
25%     30.50000  3851.778566
50%     41.00000  4987.022606
75%     53.25000  6130.023016
max     64.00000  9415.495125


## Różne rozkłady pozwalają symulować:

zjawiska naturalne (normalny),

zdarzenia rzadkie (Poissona),

wybory losowe (jednostajny, kategoryczny),

czasy oczekiwania (wykładniczy),

prawdopodobieństwa (beta, binomialny).

## 2. Najważniejsze rozkłady w NumPy (np.random)

### Rozkład jednostajny (uniform)

    np.random.uniform(low=0, high=1, size=100)

wszystkie wartości w przedziale mają równe prawdopodobieństwo
zastosowania: symulacje, losowe próbkowanie


### Rozkład normalny (gaussowski)

    np.random.normal(loc=0, scale=1, size=100)

„dzwonowy” rozkład
wiele zjawisk naturalnych


### Rozkład wykładniczy

    np.random.exponential(scale=1.0, size=100)

modeluje czas między zdarzeniami

wartości dodatnie, asymetryczny


### Rozkład Poissona

    np.random.poisson(lam=3, size=100)

liczba zdarzeń w jednostce czasu/przestrzeni
np. liczba klientów na godzinę

### Rozkład dwumianowy (binomialny)

    np.random.binomial(n=10, p=0.5, size=100)

liczba sukcesów w serii prób
np. liczba „orłów” w 10 rzutach monetą


### Rozkład beta

    np.random.beta(a=2, b=5, size=100)

wartości w przedziale [0,1]
modelowanie prawdopodobieństw


### Rozkład gamma

    np.random.gamma(shape=2.0, scale=2.0, size=100)

uogólnienie wykładniczego
modelowanie czasu życia, opóźnień


### Rozkład log-normalny

    np.random.lognormal(mean=0, sigma=1, size=100)

dane dodatnie, silnie skośne
np. dochody, ceny


### Rozkład kategoryczny (losowanie z listy)

    np.random.choice(["A", "B", "C"], size=100, p=[0.2, 0.5, 0.3])

dane jakościowe
można ustawić prawdopodobieństwa

In [2]:
np.random.seed(123)
np.random.binomial(n=1, p=0.5, size=10)

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0])

In [3]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)

df = pd.DataFrame({
    "wiek": rng.integers(18, 70, 200),
    "dochód": rng.lognormal(mean=8, sigma=0.5, size=200),
    "liczba_zakupów": rng.poisson(lam=5, size=200),
    "czas_na_stronie": rng.exponential(scale=10, size=200),
    "segment": rng.choice(["A", "B", "C"], size=200, p=[0.3, 0.5, 0.2])
})

print(df.head())

   wiek       dochód  liczba_zakupów  czas_na_stronie segment
0    22  3640.539316               4        15.261631       C
1    58  1895.542720               7         2.317415       A
2    52  2467.396248               8         2.517159       B
3    40  5707.943892               4         0.945449       C
4    40  2494.560934               5         6.624894       A


In [4]:
rng = np.random.default_rng(42)

In [6]:
rng.uniform(low=0.0, high=1.0, size=12)

array([0.43887844, 0.85859792, 0.69736803, 0.09417735, 0.97562235,
       0.7611397 , 0.78606431, 0.12811363, 0.45038594, 0.37079802,
       0.92676499, 0.64386512])

In [7]:
rng.normal(loc=0.0, scale=1.0, size=10)

array([ 1.12724121,  0.46750934, -0.85929246,  0.36875078, -0.9588826 ,
        0.8784503 , -0.04992591, -0.18486236, -0.68092954,  1.22254134])

In [10]:
rng.exponential(scale=10, size=10)

array([ 0.73028348, 11.34067502, 13.54337988, 11.22039651,  2.8004912 ,
        3.20936191,  1.65735907,  3.54363513,  0.21139756,  1.67356396])

In [16]:
rng.poisson(lam=1, size=10)

array([1, 0, 0, 0, 0, 2, 1, 1, 0, 0])

In [19]:
rng.binomial(1, 0.5, 10)

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1])

In [21]:
rng.lognormal(mean=0.0, sigma=1.0, size=10)

array([1.07479453, 0.58890364, 1.2619728 , 1.02209265, 4.96185117,
       0.78713491, 0.35933596, 1.19635045, 1.2460726 , 3.89302922])

In [22]:
rng.gamma(2, 1, 10)

array([2.9939697 , 4.35942502, 0.9696665 , 1.21237564, 2.62846619,
       0.39767373, 2.10505901, 5.80179977, 2.26095375, 0.15137741])

In [23]:
rng.beta(2, 2, 10)

array([0.4524662 , 0.70158494, 0.16015571, 0.6255812 , 0.10213302,
       0.48533106, 0.60629381, 0.69558349, 0.75384903, 0.76998727])

In [24]:
rng.integers(0, 10, 10)

array([8, 0, 7, 7, 3, 2, 0, 9, 9, 2])

In [26]:
rng.choice(["a", "b", "c"], 10)

array(['a', 'a', 'a', 'c', 'c', 'a', 'c', 'a', 'b', 'b'], dtype='<U1')

# Zadania

## Zadanie 1 — Dane demograficzne populacji

Cel: symulacja uproszczonej populacji osób.

Kolumny i charakterystyka:

wiek – liczba całkowita, zakres 0–90 → rng.integers(0, 91) (rozkład dyskretny jednostajny)

płeć – kategoria: "M", "K" → rng.choice(["M","K"]) (rozkład kategoryczny, p≈0.5/0.5)

wzrost_cm – liczba rzeczywista → rng.normal(170, 10) (rozkład normalny)

waga_kg – liczba rzeczywista → rng.normal(70, 15) (rozkład normalny)

Uwagi: można dodać zależność między wzrostem a wagą.

## Zadanie 2 — Dane klientów sklepu internetowego

Cel: symulacja zachowania użytkowników.

Kolumny:

liczba_wizyt – liczba całkowita
→ rng.poisson(5) (Poisson)

czas_na_stronie – liczba rzeczywista (minuty)
→ rng.exponential(10) (wykładniczy)

wydatki – liczba rzeczywista
→ rng.lognormal(4, 1) (log-normalny)

segment – kategoria: "A","B","C"
→ rng.choice([...], p=[0.3,0.5,0.2])


Uwagi: wydatki zwykle są silnie skośne.

## Zadanie 3 — Wyniki egzaminu

Cel: modelowanie wyników testu.

Kolumny:

wynik – liczba całkowita (0–100)
→ rng.normal(60, 15) + przycięcie zakresu

czas_rozwiązywania – liczba rzeczywista
→ rng.normal(60, 10)

zaliczony – 0/1
→ wynik > 50 (deterministycznie) lub rng.binomial(1, 0.7)

grupa – kategoria ("A","B")
→ rng.choice([...])

Uwagi: można badać zależność czasu od wyniku.

## Zadanie 4 — Dane sensorów (IoT)

Cel: symulacja pomiarów z urządzeń.

Kolumny:

temperatura – liczba rzeczywista
→ rng.normal(20, 5)

wilgotność – liczba rzeczywista (0–100)
→ rng.uniform(30, 90)

liczba_zdarzeń – liczba całkowita
→ rng.poisson(2)

czas_między_zdarzeniami – liczba rzeczywista
→ rng.exponential(5)

Uwagi: typowe dane czasowe i pomiarowe.

## Zadanie 5 — Symulacja rynkowa (dochody)

Cel: modelowanie nierówności ekonomicznych.

Kolumny:

dochód – liczba rzeczywista
→ rng.lognormal(8, 0.7)

wydatki – liczba rzeczywista
→ funkcja dochodu + szum (normal)

oszczędności – liczba rzeczywista
→ dochód – wydatki

klasa_społeczna – kategoria
→ rng.choice(["niska","średnia","wysoka"], p=[0.5,0.4,0.1])


Uwagi: silna skośność i zależności między zmiennymi.

## Zadanie 6 — Dane eksperymentalne (zależność liniowa)

Cel: przygotowanie danych do regresji.

Kolumny:

x – liczba rzeczywista
→ np.linspace(0, 10, n)

noise – liczba rzeczywista
→ rng.normal(0, 1)

y – liczba rzeczywista
→ y = 3x + 2 + noise
grupa – kategoria ("kontrola","eksperymentalna")
→ rng.choice([...])


Uwagi: klasyczny przypadek do analizy korelacji i regresji.