<a href="https://colab.research.google.com/github/kzdanowski/KGN_Programowanie2/blob/main/Lab/P2Lab04_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

## 1. Importowanie i Podstawy

In [ ]:
import numpy as np

# Tworzenie tablic (Arrays)
2. Podstawowym obiektem w NumPy jest ndarray. Różni się on od listy w Pythonie tym, że musi przechowywać elementy tego samego typu, co pozwala na ogromne przyspieszenie obliczeń.

Python
# Zwykła lista vs Tablica NumPy

    lista = [1, 2, 3, 4, 5]
    arr = np.array(lista)

# Tablice wypełnione konkretnymi wartościami

    zera = np.zeros((3, 3))        # Macierz 3x3 samych zer
    jedynki = np.ones((2, 4))      # Macierz 2x4 samych jedynek
    zakres = np.arange(0, 10, 2)   # Od 0 do 10 (bez 10) co 2
    liniowe = np.linspace(0, 1, 5) # 5 równo rozłożonych liczb od 0 do 1
    losowe = np.random.rand(2, 2)  # Losowe wartości z przedziału [0, 1)


3. Atrybuty i Kształt (Shape)
Zrozumienie wymiarów jest kluczowe w algebrze liniowej.

    A = np.array([[1, 2, 3], [4, 5, 6]])

    print(f"Wymiary (ndim): {A.ndim}")
    print(f"Kształt (shape): {A.shape}") # (wiersze, kolumny)
    print(f"Typ danych: {A.dtype}")

# Zmiana kształtu (Reshaping)

    B = np.arange(12).reshape(3, 4)
    print(B)

4. Operacje matematyczne (Element-wise)

W NumPy operacje są wykonywane na każdym elemencie z osobna (tzw. wektoryzacja).

    x = np.array([1, 2, 3])
    y = np.array([4, 5, 6])

    print(x + y)  # [5, 7, 9]
    print(x * 2)  # [2, 4, 6]
    print(x ** 2) # [1, 4, 9]
    print(np.sin(x))

5. Algebra Liniowa

Używamy modułu np.linalg lub dedykowanych operatorów.

Mnożenie macierzy
Pamiętaj: operacja * to mnożenie element po elemencie. Aby pomnożyć macierze zgodnie z zasadami algebry, używamy @ lub .dot().


    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

## Mnożenie macierzowe

    C = A @ B

Lub:

    C = np.dot(A, B)

# Transpozycja

    print(A.T)

# Wyznacznik macierzy (Determinant)

    det = np.linalg.det(A)

# Macierz odwrotna

    A_inv = np.linalg.inv(A)

# Rozwiązywanie układu równań Ax = b

    1x + 2y = 5
    3x + 4y = 11

    b = np.array([5, 11])

    rozwiazanie = np.linalg.solve(A, b)
    print(f"Wynik układu równań: {rozwiazanie}")


6. Agregacja danych
Szybkie statystyki na dużych zbiorach danych.


    data = np.array([[1, 2], [3, 4]])

    print(np.sum(data))          # Suma wszystkich elementów

    print(np.mean(data, axis=0)) # Średnia z kolumn

    print(np.max(data, axis=1))  # Maksimum z wierszy

In [ ]:
A = np.array([[1, 2], [3, 4]])

b = np.array([5, 11])
np.linalg.solve(A, b)

array([1., 2.])

## 2. Zadania do wykonania
Uzupełnij poniższe komórki kodu zgodnie z poleceniami.

### Zadanie 1: Budowanie fundamentów
Stwórz tablicę 20 elementów od 10 do 30. Wypisz co drugi element i odwróć kolejność.

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10])

### Zadanie 2: Reshape
Przekształć wektor 12 liczb w macierz 3x4 oraz 2x6.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### Zadanie 3: Filtrowanie
Z tablicy 10 losowych liczb (0-100) wybierz tylko te > 50.

array([78, 73, 63, 72, 92, 94])

### Zadanie 4: Statystyka
Stwórz macierz 5x5 (random). Oblicz średnią kolumn i sumę wierszy.

array([[48, 81, 33, 64, 57],
       [17, 15, 36, 80, 66],
       [15,  1, 71, 12, 93],
       [18, 23,  4, 49, 21],
       [81, 84, 14, 73,  6]])

array([283, 214, 192, 115, 258])

### Zadanie 5: Szachownica
Stwórz macierz 8x8 z układem zer i jedynek jak na szachownicy.

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Zadanie 6: Mnożenie Macierzy
Pomnóż macierze A i B (macierzowo, nie elementowo).

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])



array([[19, 22],
       [43, 50]])

### Zadanie 7: Układ równań
Rozwiąż układ równań:

2x + 3y + 1z = 1

4x + 1y - 3z = 11

2x - 1y + 2z = 5

array([ 2.56, -1.16, -0.64])

### Zadanie 8: Normalizacja Min-Max
Przeskaluj wektor [10, 20, 30, 40, 50] do zakresu 0-1.

$$v_{new} = \frac{v - min(v)}{max(v) - min(v)}$$

array([0.  , 0.25, 0.5 , 0.75, 1.  ])